### ISSUE TITLE
Replacing (removing) subtrees of AST

### ISSUE THREAD

**Issue by yjunechoe** [JorisChau/rrapply#15]
Hi! Thanks for this awesome package. I have a usecase question - I hope it's ok to post it as an issue.

I'm working with `rrapply()` to wrangle `<formula>` objects. Specifically, I wanted to replicate the functionality of two utility functions from `{lme4}`:

```r
library(lme4)
fm <- y ~ a + b + (c | d) + (e || f)

nobars(fm)
#> y ~ a + b

findbars(fm)
#> [[1]]
#> c | d
#> 
#> [[2]]
#> 1 | f
#> 
#> [[3]]
#> 0 + e | f
```

Note that `lme4::findbars()` eagerly diffuses `(e || f)` into `1 | f` and `0 + e | f`. I actually didn't want this behavior and indeed `rrapply()` gave me a very satisfactory solution towards that end:

```r
library(rrapply)
is_bar_parens <- \(x, .xsiblings) {
  identical(x, quote(`(`)) &&
    list(.xsiblings[[2]][[1]]) %in% expression(`|`, `||`)
}

findbars2 <- function(term) {
  rrapply(
    term,
    condition = is_bar_parens,
    f = \(x, .xsiblings) .xsiblings[[2]],
    how = "flatten"
  )
}

findbars2(fm)
#> [[1]]
#> c | d
#> 
#> [[2]]
#> e || f
```

For completeness, I wanted to see if I could also reimplement `lme4::nobars()` as-is using `rrapply()`, but this turned out to be a harder task. I've toyed around with `how = "recurse"` and `how = "replace"` to no avail. I know that the below is embarrassingly incorrect, but I was hoping that there's some way to express "replace this node *and its siblings and children*":

```r
rrapply(
    fm,
    condition = is_bar_parens,
    f = \(x) NULL,
    how = "replace"
)
#> y ~ a + b + NULL(c | d) + NULL(e || f)
```

Thanks in advance!

**Comment by JorisChau** [comment]
@yjunechoe: there is no easy way to prune terms from a `language` object with `rrapply`, since removing individual nodes of the syntax tree may create an invalid object. For instance, dropping only the terms `(c | d)` and `(e || f)` would produce an invalid formula (`y ~ a + b + ? + ?`). 

Here is a possible workaround where we replace the group terms `(c | d)` and `(e || f)` with valid dummy (intercept) terms and then rely on `update.formula()` to nicely clean up the formula:

```r
fm <- y ~ a + b + (c | d) + (e || f)

## replace all group terms by 1
fm1 <- rrapply(
  fm,
  class = "language",
  condition = \(x) identical(x[[1]], quote(`(`)) && list(x[[2]][[1]]) %in% expression(`|`, `||`),
  f = \(x) 1,
  how = "replace"
)
fm1
#> y ~ a + b + 1 + 1

## clean up dummy 1's
update(fm1, ~ .)
#> y ~ a + b
```

This solution assumes that the group terms are listed in parentheses as in your example, i.e. the `condition` needs to be generalized to handle formulas without parentheses, such as `y ~ a + b + c | d`.

Note: for the `findbars()` re-implementation, the `rrapply()` call could also be written slightly more compact as,

```r
rrapply(
  fm,
  class = "language",
  condition = \(x) list(x[[1]]) %in% expression(`|`, `||`),
  how = "flatten"
)
#> [[1]]
#> c | d
#> 
#> [[2]]
#> e || f
```

**Comment by yjunechoe** [comment]
Thanks for the quick response! Using `update()` that way is very clever and suitable for my usecase.

As for the intercept issue, I think I'll just grab it from `attr(terms.formula(fm), "intercept")` and use that it `f`. Happy that I can still rely on `rrapply()` for the heavy lifting.

 Cheers!
